config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  extend LanguageRouteScope

  namespace :public do
    get "statistics", to: "statistics#index"
  end

  language_scope do
    resources :groups do
      resources :people, except: [:new, :create] do
        member do
          post :send_password_instructions
          put :primary_group

          get "print" => "person/print#index"
          put "print" => "person/print#index"
          get "print/preview" => "person/print#preview"
          get "print/submit" => "person/print#submit"

          get "accounting" => "person/accounting#show"

          get "upload" => "person/upload#index"
          put "upload" => "person/upload#index"
          get "upload/show_registration_generated" => "person/upload#show_registration_generated"
          get "upload/show_contract" => "person/upload#show_contract"
          get "upload/show_sepa" => "person/upload#show_sepa"
          get "upload/show_medical" => "person/upload#show_medical"
          get "upload/show_data_agreement" => "person/upload#show_data_agreement"
          get "upload/show_passport" => "person/upload#show_passport"
          get "upload/show_recommendation" => "person/upload#show_recommendation"
          get "upload/show_data_agreement" => "person/upload#show_data_agreement"
          get "upload/show_photo_permission" => "person/upload#show_photo_permission"
          get "upload/show_good_conduct" => "person/upload#show_good_conduct"
          delete "upload/delete/:what" => "person/upload#destroy"

          get "medical" => "person/medical#show"
          get "medical/edit" => "person/medical#edit"
          put "medical" => "person/medical#update"

          get "status" => "person/status#show"
          get "status/edit" => "person/status#edit"
          put "status" => "person/status#update"
          post "status/activate_planned_custom_installments" => "person/status#activate_planned_custom_installments"
          post "status/delete_planned_custom_installments" => "person/status#delete_planned_custom_installments"
          post "status/review_documents" => "person/status#review_documents"
          post "status/approve_documents" => "person/status#approve_documents"

          get "unit" => "person/unit#show"
          post "unit/fill_cluster_code" => "person/unit#fill_cluster_code"
          post "unit/clear_cluster_code" => "person/unit#clear_cluster_code"
        end
      end

      get "map" => "group/map#index"
    end

    get "groups/:group_id/statistics/data", to: "group/statistics#statistics_data", defaults: {format: :json}

    resources :people, only: [] do
      resource :accounting, controller: "person/accounting", only: [:show]
      resource :deregistration, controller: "person/deregistration", only: [:edit, :update]
      resource :debit_return, controller: "person/debit_return", only: [:edit, :update]
    end

    scope "fin", module: "fin" do
      get :fin, path: "", to: "wsjrdp_fin#index"
      get :new_sepa_status, path: "ae/new_sepa_status", to: "accounting_entries#new_sepa_status"
      post :new_sepa_status, path: "ae/new_sepa_status", to: "accounting_entries#new_sepa_status"
      resources :accounting_entries, path: "ae", only: [:new, :create, :index, :show, :edit, :update, :destroy]
      resources :wsjrdp_camt_transactions, path: "tx", only: [:show, :update] do
        post "create_accounting_entry", to: "wsjrdp_camt_transactions#create_accounting_entry"
        post "link_accounting_entry/:accounting_entry_id", to: "wsjrdp_camt_transactions#link_accounting_entry"
      end
      resources :wsjrdp_fin_accounts, path: "acc", only: [:show, :update]
      resources :wsjrdp_direct_debit_pre_notifications, path: "pn", only: [:show, :update]
    end
  end
end

app/controllers/person/accounting_controller.rb
# frozen_string_literal: true

#  Copyright (c) 2025, 2026 German Contingent for the World Scout Jamboree 2027.
#
#  This file is part of hitobito_wsjrdp_2027 and licensed under the
#  Affero General Public License version 3 or later. See the COPYING
#  file at the top-level directory or at
#  https://github.com/smeky42/hitobito_wsjrdp_2027

class Person::AccountingController < ApplicationController
  include ContractHelper
  include WsjrdpFinHelper

  before_action :map_id_to_person_id
  before_action :authorize_action
  decorates :group, :person

  helper_method :get_entry_path
  helper_method :can_fin?
  helper_method :can_fin_admin?
  helper_method :get_installments_table_entries
  helper_method :permitted_attrs
  helper_method :extra_entry_turbo_frame

  def show
    @person ||= person
    @group ||= group

    @accounting_entries = accounting_entries
    @direct_debit_pre_notifications = direct_debit_pre_notifications
    @new_accounting_entry = new_accounting_entry(params)
    @new_accounting_entry_path = new_accounting_entry_path + "?" + URI.encode_www_form({
      "accounting_entry[subject_id]": @person.id,
      target_turbo_frame: extra_entry_turbo_frame
    })
    @new_sepa_status_path = new_sepa_status_path + "?" + URI.encode_www_form({
      "accounting_entry[subject_id]": @person.id,
      "accounting_entry[amount_cents]": 0,
      "accounting_entry[new_sepa_status]": @person.sepa_status,
      target_turbo_frame: extra_entry_turbo_frame
    })
    @edit_deregistration_path = edit_person_deregistration_path(person) + "?" + URI.encode_www_form({
      target_turbo_frame: extra_entry_turbo_frame
    })
    @edit_debit_return_path = edit_person_debit_return_path(person) + "?" + URI.encode_www_form({
      target_turbo_frame: extra_entry_turbo_frame
    })
    render :show
  end

  def permitted_attrs
    [
      :amount_eur,
      :amount_cents,
      :amount_currency,
      :description,
      :comment,
      :endtoend_id,
      :new_sepa_status,
      :value_date,
      :dbtr_name,
      :dbtr_iban,
      :dbtr_bic,
      :dbtr_address,
      :cdtr_name,
      :cdtr_iban,
      :cdtr_bic,
      :cdtr_address,
      :mandate_id,
      :mandate_date,
      :debit_sequence_type
    ]
  end

  def new_accounting_entry(params)
    if params[:accounting_entry].blank?
      entry = AccountingEntry.new(
        subject: @person,
        author: current_user,
        amount_currency: "EUR",
        new_sepa_status: @person.sepa_status,
        additional_info: {}
      )
    else
      acc_entry_params = params[:accounting_entry].permit(permitted_attrs)
      entry = AccountingEntry.new(
        subject: @person,
        author: current_user,
        amount_currency: "EUR",
        additional_info: {},
        **acc_entry_params
      )
    end
    entry
  end

  private

  def person
    @person ||= Person.find(params[:person_id])
  end

  def group
    @group ||= person.primary_group
  end

  def get_entry_path(entry)
    if entry.class.name.demodulize == WsjrdpDirectDebitPreNotification.name.demodulize
      wsjrdp_direct_debit_pre_notification_path(entry)
    else
      accounting_entry_path(entry)
    end
  end

  def can_fin?
    @can_fin = get_can_fin(person, params: params) if @can_fin.nil?
    @can_fin
  end

  def can_fin_admin?
    @can_fin_admin = get_can_fin_admin(person, params: params) if @can_fin_admin.nil?
    @can_fin_admin
  end

  def authorize_action
    authorize!(:edit, person)
  end

  def map_id_to_person_id
    params[:person_id] = params[:id] unless params.key?(:person_id)
  end

  def accounting_entries
    @accounting_entries ||= person.accounting_entries.sort_by { |e|
      e.value_date || e.created_at.to_date
    }.reverse
  end

  def direct_debit_pre_notifications
    shown_payment_status = %w[pre_notified skipped]
    @direct_debit_pre_notifications ||= person.direct_debit_pre_notifications.select { |pn|
      shown_payment_status.any?(pn.payment_status)
    }.sort_by { |e|
      e.collection_date || e.created_at.to_date
    }.reverse
  end

  def get_installments_table_entries
    installments = person.installments_cents
    total = 0
    entries = []
    installments.each do |item|
      cents = item[1]
      total += cents
      date = Date.new(item[0][0], item[0][1], 5)
      entries << {
        date: I18n.l(date, format: "%b %Y"),
        amount: format_cents_de(cents),
        total: format_cents_de(total)
      }
    end
    entries
  end

  def extra_entry_turbo_frame
    :accounting_extra_entry
  end
end

app/controllers/person/debit_return_controller.rb
# frozen_string_literal: true

#  Copyright (c) 2026 German Contingent for the World Scout Jamboree 2027.
#
#  This file is part of hitobito_wsjrdp_2027 and licensed under the
#  Affero General Public License version 3 or later. See the COPYING
#  file at the top-level directory or at
#  https://github.com/smeky42/hitobito_wsjrdp_2027

class Person::DebitReturnController < ApplicationController
  include ContractHelper
  include WsjrdpFinHelper
  include WsjrdpFormHelper

  before_action :authorize_action
  decorates :group, :person

  helper_method :target_turbo_frame
  helper_method :return_url
  helper_method :permitted_attrs

  def edit
  end

  def update
    @person ||= person
    @person.attributes = permitted_params
    if !@person.changed?
      reload_or_return notice: "Angaben zu Rücklastschriften wurden nicht verändert"
    elsif @person.save
      reload_or_return notice: "Angaben zu Rücklastschriften wurden erfolgreich geändert"
    else
      render :edit, status: :bad_request
    end
  end

  private

  def authorize_action
    authorize!(:log, person)
  end

  def person
    @person ||= Person.find(params[:person_id])
  end

  def group
    @group ||= person.primary_group
  end

  def permitted_attrs
    [
      :debit_return_issue,
      :sepa_status
    ]
  end

  def model_params
    params.require(:person)
  end

  def permitted_params
    model_params.permit(permitted_attrs)
  end

  def target_turbo_frame
    params[:target_turbo_frame]
  end

  def return_url
    return_url_or_fallback person_accounting_path(person)
  end

  def reload_or_return(notice: nil)
    if notice.present?
      flash.now[:notice] = notice
      flash.keep
    end
    respond_to do |format|
      format.html { redirect_back_or_to return_url }
      format.turbo_stream { render turbo_stream: turbo_stream.action(:location_reload, "") }
    end
  end
end

app/controllers/wsjrdp_2027/person/query_controller.rb
# frozen_string_literal: true

#  Copyright (c) 2025 German Contingent for the World Scout Jamboree 2027.
#
#  This file is part of hitobito_wsjrdp_2027 and licensed under the
#  Affero General Public License version 3 or later. See the COPYING
#  file at the top-level directory or at
#  https://github.com/smeky42/hitobito_wsjrdp_2027

module Wsjrdp2027::Person::QueryController
  extend ActiveSupport::Concern
  included do
    # Add :zero_padded_id to the search columns.
    self.search_columns.push(:zero_padded_id)   # rubocop:disable Style/RedundantSelf
  end
end

app/helpers/sheet/person/accounting.rb
# frozen_string_literal: true

module Sheet
  class Person < Base
    class Accounting < Base
      class_attribute :always_render_parent

      self.parent_sheet = Sheet::Person
      self.always_render_parent = true
    end
  end
end

app/helpers/sheet/person/medical.rb
# frozen_string_literal: true

module Sheet
  class Person < Base
    class Medical < Base
      class_attribute :always_render_parent

      self.parent_sheet = Sheet::Person
      self.always_render_parent = true
    end
  end
end

app/helpers/sheet/person/print.rb
# frozen_string_literal: true

module Sheet
  class Person < Base
    class Print < Base
      extend ActiveSupport::Concern

      self.parent_sheet = Sheet::Person
    end
  end
end

app/helpers/sheet/person/status.rb
# frozen_string_literal: true

module Sheet
  class Person < Base
    class Status < Base
      class_attribute :always_render_parent

      self.parent_sheet = Sheet::Person
      self.always_render_parent = true
    end
  end
end

app/helpers/sheet/person/unit.rb
# frozen_string_literal: true

module Sheet
  class Person < Base
    class Unit < Base
      class_attribute :always_render_parent

      self.parent_sheet = Sheet::Person
      self.always_render_parent = true
    end
  end
end

app/helpers/sheet/person/upload.rb
# frozen_string_literal: true

#  Copyright (c) 2025, German Contingent for the Worldscoutjamboree 2027. This file is part of
#  hitobito_wsjrdp_2027 and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_wsjrdp_2027.

module Sheet
  class Person < Base
    class Upload < Base
      self.parent_sheet = Sheet::Person
    end
  end
end

app/helpers/wsjrdp_2027/people_helper.rb
# frozen_string_literal: true

#  Copyright (c) 2025 German Contingent for the World Scout Jamboree 2027.
#
#  This file is part of hitobito_wsjrdp_2027 and licensed under the
#  Affero General Public License version 3 or later. See the COPYING
#  file at the top-level directory or at
#  https://github.com/smeky42/hitobito_wsjrdp_2027

module Wsjrdp2027::PeopleHelper
  include ContractHelper

  def person_accounting_path_with_group(group, person, params)
    person_accounting_path(person, params)
  end

  def format_person_sepa_mail(person)
    format_email_or_nil(person.sepa_mail)
  end

  def format_person_additional_contact_email_a(person)
    format_email_or_nil(person.additional_contact_email_a)
  end

  def format_person_additional_contact_email_b(person)
    format_email_or_nil(person.additional_contact_email_b)
  end

  def format_person_wsjrdp_email(person)
    format_email_or_nil(person.wsjrdp_email)
  end

  def format_person_moss_email(person)
    format_email_or_nil(person.moss_email)
  end

  def format_person_unit_code(person)
    make_unit_code_display(person.unit_code, not_set_text: "Nicht gesetzt", search_link: true)
  end

  def format_person_cluster_code(person)
    make_unit_code_display(person.cluster_code, not_set_text: "Nicht gesetzt", attribute: :cluster_code, search_link: true)
  end

  def format_person_status(person)
    Settings.status[person.status].presence || person.status
  end

  def format_person_sepa_status(person)
    Settings.sepa_status[person.sepa_status].presence || person.sepa_status
  end

  def format_person_deregistration_issue(person)
    auto_link_escaped_multiline(person.deregistration_issue) if person.deregistration_issue.present?
  end

  def format_person_debit_return_issue(person)
    auto_link_escaped_multiline(person.debit_return_issue) if person.debit_return_issue.present?
  end

  def format_person_deregistration_contractual_compensation_cents(person)
    format_cents_de(person.deregistration_contractual_compensation_cents, zero_cents: "")
  end

  def format_person_deregistration_actual_compensation_cents(person)
    cents = person.deregistration_actual_compensation_cents
    if cents.present?
      eur = format_cents_de(person.deregistration_actual_compensation_cents, zero_cents: "")
      "#{eur} (Eingetragener Vorschlag)"
    else
      eur = format_cents_de(person.deregistration_contractual_compensation_cents, zero_cents: "")
      "#{eur} (nach Teilnahme- und Reisebedingungen)"
    end
  end

  def format_person_deregistration_refund_cents(person)
    format_cents_de(person.deregistration_refund_cents, zero_cents: "")
  end

  def format_person_deregistration_open_cents(person)
    format_cents_de(person.deregistration_open_cents, zero_cents: "")
  end

  def format_person_amount_paid_cents(person)
    format_cents_de(person.amount_paid_cents, zero_cents: "")
  end

  def format_person_diet(person)
    Settings.diets[person.diet].presence || person.diet
  end

  private

  def format_email_or_nil(email_addr)
    mail_to(email_addr, email_addr) if email_addr.present?
  end
end

app/helpers/wsjrdp_2027/sheet/person.rb
# frozen_string_literal: true

module Wsjrdp2027::Sheet::Person
  extend ActiveSupport::Concern

  # Only these tabs can be shown, in this order.
  shown_tabs = [
    "global.tabs.info",
    "people.tabs.medical",
    "people.tabs.accounting",
    # "people.tabs.subscriptions",
    "people.tabs.print",
    "people.tabs.upload",
    # "people.tabs.invoices",  # 2026-01-03 - no invoices in Hitobito at the moment
    # "activerecord.models.message.other",
    "people.tabs.history",
    "people.tabs.log",
    "people.tabs.status",
    "people.tabs.unit",
    "people.tabs.security_tools",
    "people.tabs.colleagues",
    "activerecord.models.assignment.other"
  ]

  included do
    tab "people.tabs.print",
      :print_group_person_path,
      if: :show

    tab "people.tabs.upload",
      :upload_group_person_path,
      if: :show

    tab "people.tabs.accounting",
      :person_accounting_path_with_group,
      alt: [:accounting_group_person_path],
      if: :show

    tab "people.tabs.medical",
      :medical_group_person_path,
      alt: [:medical_edit_group_person_path],
      if: :show

    tab "people.tabs.status",
      :status_group_person_path,
      alt: [:status_edit_group_person_path],
      if: (lambda do |view, _group, person|
        view.can?(:log, person)
      end)

    tab "people.tabs.unit",
      :unit_group_person_path,
      if: (lambda do |view, _group, person|
        view.can?(:log, person)
      end)

    self.tabs.select! { |t| shown_tabs.include? t.label_key }
    self.tabs.sort_by! { |t| shown_tabs.index t.label_key }

    def current_parent_nav_path
      current? ? request.path : child.current_parent_nav_path
    end
  end
end

app/views/people/_actions_index.html.haml
-#  Copyright (c) 2012-2013, Jungwacht Blauring Schweiz. This file is part of
-#  hitobito and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito.
- if can?(:new, @group.roles.new)
  = action_button(t('.add_person'), new_group_role_path(@group), :plus)

- if can?(:create_invoices_from_list, @group)
  = invoice_button(filter: list_filter_args, group: @group)

= render_extensions :actions_index

- if can?(:new, @group.roles.new)
  = action_button(t('.import_list'), new_group_csv_imports_path, :upload)

= dropdown_people_export(index_full_ability?)

- if can?(:manage_person_duplicates, @group)
  = action_button(t('.person_duplicate_list'), group_person_duplicates_path(@group), :'user-friends')

app/views/people/_actions_show.html.haml
-#  Copyright (c) 2012-2017, Jungwacht Blauring Schweiz. This file is part of
-#  hitobito and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito.

- if can?(:edit, entry)
  = button_action_edit

- if can?(:destroy, entry)
  = button_action_destroy(nil, { class: "btn-danger", data: { confirm: t('person.confirm_delete',
                                                              person: entry.person) } })
- if can?(:create_invoice, entry)
  = invoice_button(people: [entry])

= render_extensions(:actions_show)

-# We have removed the Export dropdown from a single person view here

= dropdown_people_login(entry)

- if may_impersonate?(entry, parent)
  = action_button(t('.impersonate_user'),
                  group_person_impersonate_path(parent, entry),
                  nil,
                  data: { method: :post },
                  title: t('.impersonate_user_tooltip'))

app/views/people/_additional_contact.html.haml
-#  Copyright (c) 2025, German Contingent for the Worldscoutjamboree 2027. This file is part of
-#  hitobito_wsjrdp_2027 and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito_wsjrdp_2027.

%h2.mt-3
  = t('people.form_tabs.additional_contact')
%h4
  - if (entry.years.to_i >= 18) 
    = t('activerecord.attributes.person.additional_contact_a_info_adult')
  - else 
    = t('activerecord.attributes.person.additional_contact_a_info')
= render_attrs(entry, :additional_contact_name_a, :additional_contact_adress_a, :additional_contact_email_a, :additional_contact_phone_a)

- if entry.years.to_i >= 18 || !entry.additional_contact_single
  %h4
    - if (entry.years.to_i >= 18) 
      = t('activerecord.attributes.person.additional_contact_b_info_adult')
    - else 
      = t('activerecord.attributes.person.additional_contact_b_info')
  = render_attrs(entry, :additional_contact_name_b, :additional_contact_adress_b, :additional_contact_email_b, :additional_contact_phone_b)

app/views/people/_additional_info.html.haml
-#  Copyright (c) 2025, German Contingent for the Worldscoutjamboree 2027. This file is part of
-#  hitobito_wsjrdp_2027 and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito_wsjrdp_2027.

%h2.mt-3
  = t('people.form_tabs.additional_info')
- entry.diet = Settings.diets[entry.diet]
= render_attrs(entry, :passport_germany,
                      :passport_nationality,
                      :passport_approved,
                      :languages_spoken,
                      :diet,
                      :medical_eating_disorders,
                      :shirt_size,
                      :uniform_size,
                      :can_swim,
                      :foto_permission)

app/views/people/_association.html.haml
-#  Copyright (c) 2025, German Contingent for the Worldscoutjamboree 2027. This file is part of
-#  hitobito_wsjrdp_2027 and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito_wsjrdp_2027.

%h2.mt-3
  = t('people.form_tabs.rdp_association')
= render_attrs(entry, :rdp_association, :rdp_association_region, :rdp_association_sub_region, :rdp_association_group, :rdp_association_number)

- entry.buddy_id = "#{entry.buddy_id}-#{entry.id}"
- if can?(:log, entry)
  = render_attrs(entry, :buddy_id, :unit_code)
- else
  = render_attrs(entry, :buddy_id)

app/views/people/_attrs.html.haml
-#  Copyright (c) 2025, German Contingent for the Worldscoutjamboree 2027. This file is part of
-#  hitobito_wsjrdp_2027 and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito_wsjrdp_2027.

#main.row
  %article.col-lg
    = render 'contact_data', person: entry, only_public: cannot?(:show_details, entry)
    - if can?(:show_details, entry)
      %h2= t('.additional_data')
      %div
        = render_attrs(entry, :birthday, :gender)

        = render_extensions :details, locals: { show_full: can?(:show_full, entry) }

        - if can?(:update, entry)
          = render_attrs(entry, :created_info, :updated_info, :login_status)
        - else
          = render_attrs(entry, :created_info, :updated_info)
        - FeatureGate.if(:person_language) do
          = render_attrs(entry, :language)

        - FeatureGate.if(:self_registration_reason) do
          = render_present_attrs(entry, :self_registration_reason_text)

        -# = render 'people_relations'

      - if entry.additional_information?
        %h2= Person.human_attribute_name(:additional_information)
        %p.multiline= safe_auto_link(entry.additional_information)
    
    = render 'additional_info'
    
    = render 'additional_contact'
    
    = render_extensions :show_left


  - if can?(:show_details, entry)
    %aside.col-lg-5.offset-lg-1
      = render_extensions :data_quality
      
      = render 'status'
      = render 'association'
      = render 'participant_wish_data'
      = render 'finance'

      = render 'roles'
      = render 'add_requests'
      = render 'event_aside', title: Event::Application.model_name.human(count: 2), collection: entry.pending_applications
      = render 'participation_aside', title: upcoming_events_title, collection: entry.upcoming_participations

      = render_extensions :show_event

      = render 'qualifications', show_buttons: true

      = render(HouseholdAsideComponent.new(person: entry, group: @group))

      = render_extensions :show_right
      
      - if can?(:log, entry)
        = render 'notes/section', create_path: group_person_notes_path(@group, entry)
        = render 'tags'

app/views/people/_fields.html.haml
-#  Copyright (c) 2025, German Contingent for the Worldscoutjamboree 2027. This file is part of
-#  hitobito_wsjrdp_2027 and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito_wsjrdp_2027.


-# BEWARE: This partial is used from different places (e.g. event/register/register).
-#         Make sure not to use relative partial paths here or in any extensions
-#         unless these partials also exist in all folders referencing this file here.

- has_relations = false # TODO throws error in Staging ||= PeopleRelation.any?

= render 'form_tabs'

.tab-content
  #general.tab-pane.active

    - if (@person.status == 'registered')
      = field_set_tag do
        = f.labeled_input_fields(*entry.decorate.used_attributes(:first_name, :last_name))
    - else
      = render_attrs(entry, :first_name, :last_name)

    - if (@person.status == 'registered')
      = field_set_tag do
        = f.labeled(:gender) do
          - (Person::GENDERS + ['']).each do |key|
            = f.inline_radio_button(:gender, key, entry.gender_label(key))
    - else
      = render_attrs(entry,  :gender)

    = field_set_tag do
      = f.labeled_input_field(:pronoun)
      = f.labeled_input_fields(*entry.decorate.used_attributes(:nickname))

      = render_extensions :name_fields, locals: { f: f }

    = render 'contactable/fields', f: f

    = render 'picture_fields', f: f

    = render_extensions :fields, locals: { f: f }

    - if has_relations && PeopleRelation.possible_kinds.present?
      = field_set_tag do
        = f.labeled_inline_fields_for :relations_to_tails,
                                      'people_relation_fields',
                                      entry.relations_to_tails.includes(:tail)

    = field_set_tag do
      = f.labeled_input_field(:additional_information, help: t('.no_sensitive_information'))

  #additional_contact.tab-pane
    = render 'contactable/additional_contact_fields', f: f

  #additional_info.tab-pane
    = render 'contactable/additional_info_fields', f: f

  #association.tab-pane
    = render 'contactable/association_fields', f: f

  #finance.tab-pane
    = render 'contactable/finance_fields', f: f

app/views/people/_finance.html.haml
-#  Copyright (c) 2025, German Contingent for the Worldscoutjamboree 2027. This file is part of
-#  hitobito_wsjrdp_2027 and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito_wsjrdp_2027.

%h2.mt-3
  = t('people.form_tabs.finance')
= render_attrs(entry,
    :early_payer,
    :sepa_name,
    :sepa_address,
    :sepa_mail,
    :sepa_iban,
    :sepa_bic,
    :sepa_mandate_id)

app/views/people/_participant_wish_data_list.html.haml
- unless wish_persons.empty?
  %div
    %div
      %strong=list_title
    - wish_persons.each do |p_wish|
      %div(style="width:100%; border-radius: 10px; background-color: #F8F9FA; padding: 2px 8px; margin: 4px auto;")
        %small
          %strong
            = link_to_if(can?(:show, p_wish), "#{p_wish.first_name} #{p_wish.last_name}", group_person_path(p_wish.default_group_id, p_wish.id))
          %span="(#{mail_to(p_wish.email)})"
          %br
          - if can?(:show, p_wish) and valid_unit_code?(p_wish.unit_code)
            %span(style="display: inline-block; margin: 0 4px; width: 12px; background-color: #{p_wish.unit_code};")<>
              &nbsp;
            %span.muted="#{p_wish.buddy_id}-#{p_wish.id}"
          - else
            %span.muted(style="padding-left: 20px;")="#{p_wish.buddy_id}-#{p_wish.id}"
          %br
          %span.muted(style="padding-left: 20px;")="Status: #{Settings.status[p_wish.status]}"
          - p_full_rdp_association_group = full_rdp_association_group(p_wish)
          - if p_full_rdp_association_group != full_rdp_association_group(entry)
            %br
            %span.muted(style="padding-left: 20px;")
              %em=p_full_rdp_association_group