config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  extend LanguageRouteScope

  namespace :public do
    get "statistics", to: "statistics#index"
  end

  language_scope do
    resources :groups do
      resources :people, except: [:new, :create] do
        member do
          post :send_password_instructions
          put :primary_group

          get "print" => "person/print#index"
          put "print" => "person/print#index"
          get "print/preview" => "person/print#preview"
          get "print/submit" => "person/print#submit"

          get "accounting" => "person/accounting#show"

          get "upload" => "person/upload#index"
          put "upload" => "person/upload#index"
          get "upload/show_registration_generated" => "person/upload#show_registration_generated"
          get "upload/show_contract" => "person/upload#show_contract"
          get "upload/show_sepa" => "person/upload#show_sepa"
          get "upload/show_medical" => "person/upload#show_medical"
          get "upload/show_data_agreement" => "person/upload#show_data_agreement"
          get "upload/show_passport" => "person/upload#show_passport"
          get "upload/show_recommendation" => "person/upload#show_recommendation"
          get "upload/show_data_agreement" => "person/upload#show_data_agreement"
          get "upload/show_photo_permission" => "person/upload#show_photo_permission"
          get "upload/show_good_conduct" => "person/upload#show_good_conduct"
          delete "upload/delete/:what" => "person/upload#destroy"

          get "medical" => "person/medical#show"
          get "medical/edit" => "person/medical#edit"
          put "medical" => "person/medical#update"

          get "status" => "person/status#show"
          get "status/edit" => "person/status#edit"
          put "status" => "person/status#update"
          post "status/activate_planned_custom_installments" => "person/status#activate_planned_custom_installments"
          post "status/delete_planned_custom_installments" => "person/status#delete_planned_custom_installments"
          post "status/review_documents" => "person/status#review_documents"
          post "status/approve_documents" => "person/status#approve_documents"

          get "unit" => "person/unit#show"
          post "unit/fill_cluster_code" => "person/unit#fill_cluster_code"
          post "unit/clear_cluster_code" => "person/unit#clear_cluster_code"
        end
      end

      get "map" => "group/map#index"
    end

    get "groups/:group_id/statistics/data", to: "group/statistics#statistics_data", defaults: {format: :json}

    resources :people, only: [] do
      resource :accounting, controller: "person/accounting", only: [:show]
      resource :deregistration, controller: "person/deregistration", only: [:edit, :update]
      resource :debit_return, controller: "person/debit_return", only: [:edit, :update]
    end

    scope "fin", module: "fin" do
      get :fin, path: "", to: "wsjrdp_fin#index"
      get :new_sepa_status, path: "ae/new_sepa_status", to: "accounting_entries#new_sepa_status"
      post :new_sepa_status, path: "ae/new_sepa_status", to: "accounting_entries#new_sepa_status"
      resources :accounting_entries, path: "ae", only: [:new, :create, :index, :show, :edit, :update, :destroy]
      resources :wsjrdp_camt_transactions, path: "tx", only: [:show, :update] do
        post "create_accounting_entry", to: "wsjrdp_camt_transactions#create_accounting_entry"
        post "link_accounting_entry/:accounting_entry_id", to: "wsjrdp_camt_transactions#link_accounting_entry"
      end
      resources :wsjrdp_fin_accounts, path: "acc", only: [:show, :update]
      resources :wsjrdp_direct_debit_pre_notifications, path: "pn", only: [:show, :update]
    end
  end
end

app/controllers/fin/accounting_entries_controller.rb
# frozen_string_literal: true

class Fin::AccountingEntriesController < ApplicationController
  include WsjrdpFormHelper
  include WsjrdpFinHelper
  include FormatHelper
  include UtilityHelper
  include ::ActionView::Helpers::TagHelper

  before_action :authorize_action
  decorates :group, :person

  helper_method :entry

  helper_method :accounting_entry
  helper_method :can_fin?
  helper_method :can_fin_admin?
  helper_method :get_accounting_entry_path
  helper_method :person
  helper_method :permitted_attrs
  helper_method :cancel_url, :return_url
  helper_method :target_turbo_frame

  def entry
    @accounting_entry
  end

  def index
    authorize!(:show, AccountingEntry)
    @accounting_entries = AccountingEntry.limit(20).order(id: "desc")
  end

  def new
    authorize!(:create, AccountingEntry)
    attrs = {amount_currency: "EUR", additional_info: {}}
    attrs.update(permitted_params)
    @accounting_entry = AccountingEntry.new(attrs)
  end

  def new_sepa_status
    authorize!(:create, AccountingEntry)
    attrs = {amount_eur: 0, amount_currency: "EUR", additional_info: {}}
    attrs.update(permitted_params)
    @accounting_entry = AccountingEntry.new(attrs)
    @accounting_entry.author = current_user
    if request.post?
      save_new_sepa_status
    end
  end

  def create
    authorize!(:create, AccountingEntry)
    @accounting_entry = AccountingEntry.new(permitted_params)
    @accounting_entry.author = current_user
    if @accounting_entry.save
      notice = "Neue Buchung in Höhe von #{@accounting_entry.amount_eur_display} € erfolgreich angelegt."
      flash.now[:notice] = notice
      flash.keep
      respond_to do |format|
        format.html { redirect_back_or_to accounting_entries_path }
        format.turbo_stream { render turbo_stream: turbo_stream.action(:location_reload, "") }
      end
    else
      render :new, status: :bad_request
    end
  end

  def show
    @group ||= group
    @person ||= person
    @accounting_entry ||= accounting_entry
    @permitted_attrs ||= permitted_attrs
    render "person/accounting_entries/show"
  end

  def update
    @group ||= group
    @person ||= person
    authorize!(:log, person)
    @accounting_entry ||= accounting_entry
    @permitted_attrs ||= permitted_attrs

    unless params[:accounting_entry].blank?
      accounting_entry.attributes = params.require(:accounting_entry).permit(permitted_attrs)
      unless accounting_entry.save
        render "person/accounting_entries/show", status: :bad_request
        return
      end
    end
    redirect_to return_url
  end

  def destroy
    @accounting_entry ||= accounting_entry
    authorize!(:destroy, @accounting_entry)
    raise "Missing fin_admin to destroy accounting_entry" unless can_fin_admin?
    @accounting_entry.destroy!
    redirect_to "#{accounting_group_person_path(group, person)}?fin_admin=1"
  end

  def permitted_attrs
    if can?(:fin_admin, AccountingEntry)
      if action_name == "new_sepa_status"
        [
          :amount_cents, :amount_eur,
          :subject_type, :subject_id,
          :description, :comment,
          :new_sepa_status,
          :booking_date, :value_date
        ]
      else
        [
          :amount_cents, :amount_eur,
          :pre_notified_amount_cents, :pre_notified_amount_eur,
          :subject_type, :subject_id,
          :description, :comment,
          :new_sepa_status,
          :booking_date, :value_date,
          :endtoend_id,
          :dbtr_name, :dbtr_iban, :dbtr_bic, :dbtr_address,
          :cdtr_name, :cdtr_iban, :cdtr_bic, :cdtr_address,
          :mandate_id, :mandate_date, :debit_sequence_type
        ]
      end
    else
      [:comment]
    end
  end

  def model_params
    params.require(:accounting_entry)
  end

  def permitted_params
    model_params.permit(permitted_attrs)
  end

  def accounting_entry
    @accounting_entry ||= AccountingEntry.find(params[:id])
  end

  def person
    @person ||= accounting_entry.person
  end

  def group
    @group ||= accounting_entry.group
  end

  def authorize_action
    authorize!(:show, AccountingEntry)
  end

  def can_fin?
    can?(:show, AccountingEntry) && !param_is_false(params, :can_fin)
  end

  def can_fin_admin?
    can?(:fin_admin, AccountingEntry) && param_is_true(params, :fin_admin)
  end

  private

  def save_new_sepa_status
    subject = @accounting_entry.subject
    new_sepa_status = @accounting_entry.new_sepa_status
    if new_sepa_status != subject.sepa_status
      new_sepa_status_msg = "Finanzstatus auf #{Settings.sepa_status[new_sepa_status]} gesetzt"
      @accounting_entry.description = new_sepa_status_msg if @accounting_entry.description.blank?
      ActiveRecord::Base.transaction do
        @accounting_entry.save!
        subject.sepa_status = new_sepa_status
        subject.save!
      end
      if new_sepa_status == "ok"
        flash.now[:notice] = new_sepa_status_msg
      else
        flash.now[:warning] = new_sepa_status_msg
      end
    else
      flash.now[:notice] = "Finanzstatus bleibt #{Settings.sepa_status[new_sepa_status]}"
    end
    flash.keep
    respond_to do |format|
      format.html { redirect_back_or_to accounting_entries_path }
      format.turbo_stream { render turbo_stream: turbo_stream.action(:location_reload, "") }
    end
  rescue ActiveRecord::RecordInvalid
    render :new_sepa_status, status: :bad_request
  end

  def safe_join(array, sep = $OUTPUT_FIELD_SEPARATOR, &block)
    if block
      array = array.collect(&block).compact
    end
    super(array, sep)
  end

  def get_accounting_entry_path(entry = nil)
    accounting_entry_path(entry.nil? ? accounting_entry : entry)
  end

  def return_url
    return_url_or_fallback url_for(accounting_entry)
  end

  def cancel_url
    return_url
  end

  def target_turbo_frame
    params[:target_turbo_frame] || :new_accounting_entry_frame
  end
end

app/controllers/fin/wsjrdp_camt_transactions_controller.rb
# frozen_string_literal: true

#  Copyright (c) 2025. 2026 German Contingent for the World Scout Jamboree 2027.
#
#  This file is part of hitobito_wsjrdp_2027 and licensed under the
#  Affero General Public License version 3 or later. See the COPYING
#  file at the top-level directory or at
#  https://github.com/smeky42/hitobito_wsjrdp_2027

class Fin::WsjrdpCamtTransactionsController < ApplicationController
  include WsjrdpFormHelper
  include WsjrdpFinHelper

  before_action :map_id_to_wsjrdp_camt_transaction_id
  before_action :authorize_action

  helper_method :can_fin_admin?
  helper_method :camt_transaction
  helper_method :permitted_attrs
  helper_method :cancel_url, :return_url
  helper_method :camt_transaction_return_url
  helper_method :camt_transaction_path
  helper_method :matching_accounting_entries

  def show
    @wsjrdp_camt_transaction ||= camt_transaction
    render :show
  end

  def update
    @wsjrdp_camt_transaction ||= camt_transaction
    authorize!(:update, camt_transaction)
    camt_transaction.attributes = permitted_params
    if camt_transaction.save
      flash[:notice] = "Transaktion #{camt_transaction.id} erfolgreich aktualisiert."
      redirect_to return_url
    else
      render :show, status: :bad_request
    end
  end

  def create_accounting_entry
    authorize!(:update, camt_transaction)
    tx = camt_transaction
    subject = tx.subject
    authorize!(:update, subject)
    entry = AccountingEntry.create!(
      subject: subject,
      author: current_user,
      amount_cents: tx.amount_cents,
      amount_currency: tx.amount_currency,
      description: tx.description,
      comment: tx.comment,
      value_date: tx.value_date,
      booking_date: tx.booking_date,
      mandate_id: tx.mandate_id,
      endtoend_id: tx.endtoend_id,
      cdtr_name: tx.cdtr_name,
      cdtr_iban: tx.cdtr_iban,
      cdtr_bic: tx.cdtr_bic,
      cdtr_address: tx.cdtr_address,
      dbtr_name: tx.dbtr_name,
      dbtr_iban: tx.dbtr_iban,
      dbtr_bic: tx.dbtr_bic,
      dbtr_address: tx.dbtr_address,
      return_reason: tx.return_reason,
      camt_transaction_id: tx.id
    )
    tx.accounting_entry_id = entry.id
    tx.save!
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.action(:refresh, "") }
      format.html { redirect_to tx.fin_account }
    end
  end

  def link_accounting_entry
    authorize!(:update, camt_transaction)
    tx = camt_transaction
    subject = tx.subject
    authorize!(:update, subject)
    accounting_entry = AccountingEntry.find(params[:accounting_entry_id])
    accounting_entry.camt_transaction_id = tx.id
    tx.accounting_entry_id = accounting_entry.id
    tx.save!
    accounting_entry.save!
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.action(:refresh, "") }
      format.html { redirect_to tx.fin_account }
    end
  end

  private

  def map_id_to_wsjrdp_camt_transaction_id
    params[:wsjrdp_camt_transaction_id] = params[:id] unless params.key?(:wsjrdp_camt_transaction_id)
  end

  def authorize_action
    authorize!(:show, camt_transaction)
  end

  def camt_transaction
    @camt_transaction ||= WsjrdpCamtTransaction.find(params[:wsjrdp_camt_transaction_id])
  end

  def camt_transaction_path(entry = nil)
    url_for(entry.nil? ? camt_transaction : entry)
  end

  def return_url
    return_url_or_fallback url_for(camt_transaction)
  end

  def cancel_url
    return_url
  end

  def camt_transaction_return_url(entry = nil)
    params[:return_url].presence || camt_transaction_path(entry)
  end

  def can_fin_admin?
    @can_fin_admin = get_can_fin_admin(camt_transaction, params: params) if @can_fin_admin.nil?
    @can_fin_admin
  end

  def matching_accounting_entries
    @matching_accounting_entries ||= camt_transaction.accounting_entries_for_subject.select { |e|
      e.amount_cents == camt_transaction.amount_cents
    }
  end

  def _transform_tx_params(params)
    if params[:subject].blank? || params[:subject_id].blank?
      params[:subject_id] = nil
      params[:subject_type] = nil
    elsif params[:subject_type].blank?
      params[:subject_type] = "Person"
    end
    params.except(:subject)
  end

  def model_params
    params.require(:wsjrdp_camt_transaction)
  end

  def permitted_attrs
    [
      :comment,
      :subject, :subject_id, :subject_type,
      :accounting_entry, :accounting_entry_id,
      :return_status
    ]
  end

  def permitted_params
    _transform_tx_params(model_params.permit(permitted_attrs))
  end
end

app/helpers/sheet/fin/accounting_entry.rb
# frozen_string_literal: true

#  Copyright (c) 2025 German Contingent for the World Scout Jamboree 2027.
#
#  This file is part of hitobito_wsjrdp_2027 and licensed under the
#  Affero General Public License version 3 or later. See the COPYING
#  file at the top-level directory or at
#  https://github.com/smeky42/hitobito_wsjrdp_2027

module Sheet
  class Fin::AccountingEntry < Base
    self.parent_sheet = Sheet::Person

    def title
      "Buchung #{entry.id}"
    end

    def current_parent_nav_path
      view.person_accounting_path(entry.person)
    end
  end
end

app/helpers/sheet/fin/wsjrdp_camt_transaction.rb
# frozen_string_literal: true

#  Copyright (c) 2025 German Contingent for the World Scout Jamboree 2027.
#
#  This file is part of hitobito_wsjrdp_2027 and licensed under the
#  Affero General Public License version 3 or later. See the COPYING
#  file at the top-level directory or at
#  https://github.com/smeky42/hitobito_wsjrdp_2027

module Sheet
  class Fin::WsjrdpCamtTransaction < Base
    def title
      "Konto-Transaktion #{entry.id}"
    end
  end
end

app/helpers/sheet/fin/wsjrdp_direct_debit_pre_notification.rb
# frozen_string_literal: true

#  Copyright (c) 2025 German Contingent for the World Scout Jamboree 2027.
#
#  This file is part of hitobito_wsjrdp_2027 and licensed under the
#  Affero General Public License version 3 or later. See the COPYING
#  file at the top-level directory or at
#  https://github.com/smeky42/hitobito_wsjrdp_2027

module Sheet
  class Fin::WsjrdpDirectDebitPreNotification < Base
    self.parent_sheet = Sheet::Person

    def title
      "Lastschrift Pre-Notification #{entry.id}"
    end

    def current_parent_nav_path
      view.person_accounting_path(entry.person)
    end
  end
end

app/helpers/sheet/fin/wsjrdp_fin.rb
# frozen_string_literal: true

#  Copyright (c) 2026 German Contingent for the World Scout Jamboree 2027.
#
#  This file is part of hitobito_wsjrdp_2027 and licensed under the
#  Affero General Public License version 3 or later. See the COPYING
#  file at the top-level directory or at
#  https://github.com/smeky42/hitobito_wsjrdp_2027

module Sheet
  class Fin::WsjrdpFin < Base
    def title
      "Finanzen"
    end
  end
end

app/helpers/sheet/fin/wsjrdp_fin_account.rb
# frozen_string_literal: true

#  Copyright (c) 2025 German Contingent for the World Scout Jamboree 2027.
#
#  This file is part of hitobito_wsjrdp_2027 and licensed under the
#  Affero General Public License version 3 or later. See the COPYING
#  file at the top-level directory or at
#  https://github.com/smeky42/hitobito_wsjrdp_2027

module Sheet
  class Fin::WsjrdpFinAccount < Base
    def title
      "#{entry.short_name} (Konto #{entry.id})"
    end
  end
end

app/views/fin/accounting_entries/_accounting_entry_form.html.haml
-#  Copyright (c) 2025, 2026 German Contingent for the World Scout Jamboree 2027.
-#
-#  This file is part of hitobito_wsjrdp_2027 and licensed under the
-#  Affero General Public License version 3 or later.
-#  See the COPYING file at the top-level directory or at
-#  https://github.com/smeky42/hitobito_wsjrdp_2027

-# input: f - form

= field_set_tag do
  -# = f.labeled_collection_select(:new_sepa_status, Settings.sepa_status, :first, :last, {})
  -# %div.border-top.py-2
  - if f.object.subject_id.present?
    = f.hidden_field :subject_id
    = form_like_labeled_attr(f.object, :subject_id, display_link: false)
  - else
    = f.labeled_person_field :subject
  = input_or_render_attrs(f, :amount_eur)
  = f.labeled_input_field :description
  = f.labeled_input_field :comment, help_inline: 'Nur sichtbar für Personen mit Buchhaltungs-Rechten'
  %div.border-top.py-2
  = f.labeled_input_field :value_date, help_inline: 'Nur falls abweichend vom aktuellen Datum'
  = f.labeled_input_field :endtoend_id, help_inline: 'SEPA Ende-zu-Ende-Referenz'
  %div.border-top.py-2
  = f.labeled_input_fields :dbtr_name, :dbtr_iban, :dbtr_bic, :dbtr_address
  %div.border-top.py-2
  %div.row.mb-2.mt-0
    %div.offset-md-3.offset-xl-2
      %div.btn-group
        %button.btn.btn-sm.btn-outline-primary.mt-2{ type: 'button', onclick: 'fill_in_rdp_account_44_as_creditor()' }
          = t('activerecord.attributes.accounting_entry.fill_in_rdp_account_44_as_creditor')
      %div.btn-group
        %button.btn.btn-sm.btn-outline-primary.mt-2{ type: 'button', onclick: 'clear_creditor()' }
          = t('activerecord.attributes.accounting_entry.clear_creditor')
  = f.labeled_input_fields :cdtr_name, :cdtr_iban, :cdtr_bic, :cdtr_address
  %div.border-top.py-2

app/views/fin/accounting_entries/_accounting_entry_javascript_helpers.html.haml
-#  Copyright (c) 2025, 2026 German Contingent for the World Scout Jamboree 2027.
-#
-#  This file is part of hitobito_wsjrdp_2027 and licensed under the
-#  Affero General Public License version 3 or later.
-#  See the COPYING file at the top-level directory or at
-#  https://github.com/smeky42/hitobito_wsjrdp_2027

:javascript
  function fill_in_rdp_account_44_as_creditor() {
    $('#accounting_entry_cdtr_name').val('Ring deutscher Pfadfinder*innenverbände e.V.');
    $('#accounting_entry_cdtr_iban').val('DE13370601932001939044');
    $('#accounting_entry_cdtr_bic').val('GENODED1PAX');
    $('#accounting_entry_cdtr_address').val('Chausseestraße 128/129, 10115 Berlin');
  }
  function clear_creditor() {
    $('#accounting_entry_cdtr_name').val('');
    $('#accounting_entry_cdtr_iban').val('');
    $('#accounting_entry_cdtr_bic').val('');
    $('#accounting_entry_cdtr_address').val('');
  }

app/views/fin/accounting_entries/index.html.haml
-#  Copyright (c) 2025, 2026 German Contingent for the World Scout Jamboree 2027.
-#
-#  This file is part of hitobito_wsjrdp_2027 and licensed under the
-#  Affero General Public License version 3 or later.
-#  See the COPYING file at the top-level directory or at
-#  https://github.com/smeky42/hitobito_wsjrdp_2027

#main.row
  %div
    = turbo_frame_tag(:new_accounting_entry_frame, target: "_top") do
      = action_button("Neue Buchung", new_accounting_entry_path,
                      :plus, remote: false, data: {turbo_frame: "new_accounting_entry_frame"})

  %h1 Buchungen
  = render 'person/accounting/accounting_entries', entries: @accounting_entries

app/views/fin/accounting_entries/new.html.haml
-#  Copyright (c) 2025, 2026 German Contingent for the World Scout Jamboree 2027.
-#
-#  This file is part of hitobito_wsjrdp_2027 and licensed under the
-#  Affero General Public License version 3 or later.
-#  See the COPYING file at the top-level directory or at
-#  https://github.com/smeky42/hitobito_wsjrdp_2027

#main.row
  = turbo_frame_tag_if_frame_request(target_turbo_frame) do
    = render 'accounting_entry_javascript_helpers'
    %div.new-accounting-entry
      = standard_form(entry, {url: accounting_entries_path, method: :post }) do |f|
        .mt-3
        = hidden_field_tag("fin_admin", can_fin_admin?)
        = hidden_field_tag("return_url", return_url)
        = f.error_messages
        = hidden_field_tag 'target_turbo_frame', target_turbo_frame
        = form_buttons(f, submit_label: "Buchung anlegen", cancel_url: cancel_url)
        = render 'accounting_entry_form', f: f
        = form_buttons(f, submit_label: "Buchung anlegen", cancel_url: cancel_url)

app/views/fin/accounting_entries/new_sepa_status.html.haml
-#  Copyright (c) 2025, 2026 German Contingent for the World Scout Jamboree 2027.
-#
-#  This file is part of hitobito_wsjrdp_2027 and licensed under the
-#  Affero General Public License version 3 or later.
-#  See the COPYING file at the top-level directory or at
-#  https://github.com/smeky42/hitobito_wsjrdp_2027

#main.row
  = turbo_frame_tag_if_frame_request(target_turbo_frame) do
    = render 'accounting_entry_javascript_helpers'
    %div.new-sepa-status
      = standard_form(entry, {url: new_sepa_status_path, method: :post }) do |f|
        .mt-3
        = hidden_field_tag("fin_admin", can_fin_admin?)
        = hidden_field_tag("return_url", return_url)
        = f.error_messages
        = form_buttons(f, submit_label: "Finanzstatus ändern", cancel_url: cancel_url)
        = hidden_field_tag 'target_turbo_frame', target_turbo_frame
        = f.hidden_field :subject_id
        = f.hidden_field :description
        = f.hidden_field :amount_cents
        = f.labeled_collection_select(:new_sepa_status, Settings.sepa_status, :first, :last, {})
        = f.labeled_input_field :comment, help_inline: 'Nur sichtbar für Personen mit Buchhaltungs-Rechten'
        = form_buttons(f, submit_label: "Finanzstatus ändern", cancel_url: cancel_url)